version: '3.5'
services:
  producer:
    build: .
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - "8080:8080"
    volumes:
      - "/kevink:/wordcloud-producer"
    networks:
      - network
networks:
  network:
    name: backend
    external: true